query getAllManagement(
    $locale: LanguageCodeFilterEnum,  
  ) {
  getAllManagement: allManagement(first: 100, where: {language: $locale, orderby: {field: MENU_ORDER, order: ASC}}) {
    edges {
      node {
        id
        title
        slug
        ManagementPosition {
          position
        }
        featuredImage {
          node {
            sourceUrl(size: MEDIUM_LARGE)
            uri
            mediaItemUrl
            caption
            altText
          }
        }
        translation(language: UK) {
          slug
        }
      }
      cursor
    }
  }
}