query getManagement($slug: String, $locale: LanguageCodeEnum!) {
  getManagement: managementBy(slug: $slug) {
    translation(language: $locale) {
      managementPosition {
        position
      }
      content
      id
      slug
      title
      featuredImage {
          node {
            sourceUrl(size: _1536X1536)
            uri
            mediaItemUrl
            caption
            altText
          }
      }
      seo {
        title
        metaDesc
        opengraphImage {
          sourceUrl
        }
      }
    }
  }
}