query getMenu($locale: LanguageCodeFilterEnum,) {
  getMenu: menuItems(where: {language: $locale, location: MENU_1}, first: 100) {
    edges {
      node {
        id
        label
        path
        parentId
        formenu {
          menuDescription
        }
        childItems {
          edges {
            node {
              id
              label
              path
              childItems {
                edges {
                  node {
                    id
                    label
                    path
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}