query getMainPage($locale: LanguageCodeEnum!) {
  getMainPage: pageBy(uri: "holovna") {
    translation(language: $locale) {
      id
      title
      slug
      mainpage {
        herovideoblock {
          title
          description
          videolink {
            mediaItemUrl
          }
          videocover {
            sourceUrl(size: _1536X1536)
            uri
            mediaItemUrl
          }
          fieldGroupName
        }
      }
      blocks {
        attributesJSON
        dynamicContent
        originalContent
        saveContent
      }
      seo {
        title
        metaDesc
        opengraphImage {
          sourceUrl
          }
        }
    }
  }
}