query getPages($uri: String, $locale: LanguageCodeEnum!) {
  getPages: pageBy(uri: $uri) {
    translation(language: $locale) {
      id
      title
      date
      slug
      featuredImage {
        node {
          sourceUrl(size: _1536X1536)
          uri
          mediaItemUrl
          caption
          altText
        }
      }
      blocks {
        ... on CoreHeadingBlock {
          dynamicContent
          attributes {
            ... on CoreHeadingBlockAttributes {
              content
            }
          }
        }
        ... on CoreGalleryBlock {
            __typename
          innerBlocks {
            ... on CoreImageBlock {
              mediaItem {
                node {
                  link
                }
              }
            }
          }
        }
        ... on CoreParagraphBlock {
          dynamicContent
          attributes {
            ... on CoreParagraphBlockAttributes {
              align
              anchor
              content
            }
          }
        }
      }
      seo {
        title
        metaDesc
        opengraphImage {
          sourceUrl
        }
      }
    }
  }
}